# Generated by Django 5.1.6 on 2025-02-23 16:22

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_student_city_student_latitude_student_longitude_and_more"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={
                "ordering": ["school", "registration_number"],
                "verbose_name": "Bus",
                "verbose_name_plural": "Buses",
            },
        ),
        migrations.RemoveField(
            model_name="bus",
            name="gps_device_id",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="vehicle_type",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="vin",
        ),
        migrations.RemoveField(
            model_name="safetycheckitem",
            name="is_required",
        ),
        migrations.AddField(
            model_name="bus",
            name="fitness_certificate_expiry",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("DIESEL", "Diesel"),
                    ("CNG", "CNG"),
                    ("ELECTRIC", "Electric"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus",
            name="insurance_expiry",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 23, 16, 21, 13, 21948, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus",
            name="last_maintenance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="make",
            field=models.CharField(default="fwegfwrg", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus",
            name="model",
            field=models.CharField(default="Model", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bus",
            name="next_maintenance_due",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="year",
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BusDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INSURANCE", "Insurance"),
                            ("FITNESS", "Fitness Certificate"),
                            ("PERMIT", "Permit"),
                            ("TAX", "Road Tax"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(max_length=50)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("document_file", models.FileField(upload_to="bus_documents/")),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.bus",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bus", "document_type"],
                "unique_together": {("bus", "document_type")},
            },
        ),
    ]
